---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[nace-ckan::database_server]
      - recipe[nace-ckan::solr]
      - recipe[nace-ckan::default]
    attributes:
      postgresql:
        password:
          postgres: testing
      ckan:
        config:
          postgresql_url: postgresql://ckan_default:changeme@localhost/ckan
        system_user: vagrant
        db_username: ckan_default
        db_password: changeme
        db_name: ckan
        db_address: localhost
