name 'nace-ckan'
maintainer 'UAF GINA'
maintainer_email 'support+chef@gina.alaska.edu'
license 'mit'
description 'Installs/Configures nace-ckan'
long_description 'Installs/Configures nace-ckan'
version '1.1.4'

depends 'httpd', '= 0.3.5'
depends 'solr', '~> 0.5.0'
depends 'postgresql', '~> 4.0.0'
depends 'database'
depends 'poise-python', '~> 1.5.1'
