name 'nace-ckan'
maintainer 'UAF GINA'
maintainer_email 'support+chef@gina.alaska.edu'
license 'mit'
description 'Installs/Configures nace-ckan'
long_description 'Installs/Configures nace-ckan'
version '1.2.10'

depends 'httpd'
depends 'solr'
depends 'postgresql'
depends 'database'
depends 'poise-python'
