default['ckan']['db_name'] = "ckan"
default['ckan']['db_datastore_name'] = "datastore_default"
default['ckan']['db_username'] = "ckan_default"
default['ckan']['db_password'] = "pass"
default['ckan']['db_address'] = "localhost"
default['ckan']['site_url'] = "localhost"
